### ISSUE TITLE
Troubles testing Tutorials

### ISSUE THREAD

**Issue by beniroquai** [dkumor/rtcbot#18]
I went through the basic and streaming tutorials, but apparently none of them seem to work. I tested it on a Raspberry Pi and a Mac, but I cannot stream anything. I do that on a ```localhost``` so firewalls or anything like that should not be a problem. 
Is there any specific python version you are working with? Is there any simple way to debug it?

**Comment by dkumor** [comment]
Can you specify what is meant by not working? Are things not connecting? 

I will check if there was an update to a dependency that broke things.

**Comment by dkumor** [comment]
So after updating everything still works on my side - please specify which tutorials are failing for you, any error messages, and the precise code/environment being used.
