### ISSUE TITLE
missing javascript

### ISSUE THREAD

**Issue by rasmuspjohansson** [dkumor/rtcbot#2]
Hi, 
Trying to follow your tuturial but there seem to be a javascript missing 
rtcbot/examples/streaming$ python3 skeleton.py 

gives

No such file or directory: '/home/rasmus/rtcbot/examples/streaming/rtcbot/rtcbot.js

looking forward to geting this up and running :-)

**Comment by dkumor** [comment]
I am guessing that you did not install rtcbot using pip, but rather cloned the repository. There are two ways to fix the issue:

## Install using pip
```
pip install rtcbot
```

## Make the js library

The javascript  is in the js folder, and needs to be built. To do this, starting from the rtcbot directory
```
cd js
npm i --dev # Set up the js requirements
```

Then, back in the rtcbot directory:
```
make js
```

I will look into simplifying this procedure, and add these instructions to the README

**Comment by dkumor** [comment]
I have modified the makefile to simplify installation. If you pull the most recent version, building the javascript is just a matter of running
```
make js
```
in the root directory

**Comment by rasmuspjohansson** [comment]
I did install rtcbot with pip3 but cloned the github page and tried to run the code in the example folder.
My problem was that python finds the javascript.py in the code obtained via git instead of the javascript.py that you get with the pip instalation of rtcbot. 
moving the examples to a another location before testing them removed this problem. 
Thank you for a great project!
