### ISSUE TITLE
signaling works but webrtc conection lets nothing trhough when browser and robot are on separate networks

### ISSUE THREAD

**Issue by rasmuspjohansson** [dkumor/rtcbot#4]
The examples in the examples/mobile runs fine as long as the robot and the pc that opens the browser are on the same network. but something is wrong when on different networks.
what I tested:

server on digital ocean ,robot running on laptop and browser on laptop works fine  

server on digital ocean ,robot running on rpi conected to office wifi ,browser on laptop conected to office wifi works fine

server on digital ocean ,robot running on rpi conected to iphone hotspot ,browser on laptop conected to iphone -hotspot works fine
but..
if I connect the rpi robot to the office wifi and my laptop with browser to iphone hotspot. Then the signaling seem to work fine but no data is passing through the webrtc conection.
the offer and answer looks like this. 

(│·····   is an artifact from my tmux window)

{'type': 'offer', 'sdp': 'v=0\r\no=- 6647459686298250467 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=video 37680 UDP/[0/1997]│·····
SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123\r\nc=IN IP4 62.44.138.138\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=candidate:328666875 1 udp 2113937151 17│·····
2.20.10.2 35892 typ host generation 0 network-cost 999\r\na=candidate:842163049 1 udp 1677729535 62.44.138.138 37680 typ srflx raddr 172.20.10.2 rport 35892 generation│·····
 0 network-cost 999\r\na=ice-ufrag:Rmlv\r\na=ice-pwd:zvddVZUvnIYTF6Vpc02i78Yb\r\na=ice-options:trickle\r\na=fingerprint:sha-256 03:7D:3D:06:8C:7C:FF:B4:FB:87:BF:F3:D0:│·····
94:F9:38:67:B9:35:F9:04:E4:A4:A4:B5:FE:D3:25:CF:23:D0:AF\r\na=setup:actpass\r\na=mid:0\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:13 http://www.webr│·····
tc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:12 urn:3gpp:video-orientation\r\na=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensi│·····
ons-01\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=ext│·····
map:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 http://www.web│·····
rtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:5 │·····
urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 t│·····
ransport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98│·····
 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=f│·····
mtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack p│·····
li\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 transport-cc\r\na=│·····
rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:12│·····
2 rtx/90000\r\na=fmtp:122 apt=102\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\│·····
na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f\r\na=rtpmap:121 rtx/90000\r\na=fmtp:121 apt=127\r\na=rtpma│·····
p:125 H264/90000\r\na=rtcp-fb:125 goog-remb\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-│·····
asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:107 rtx/90000\r\na=fmtp:107 apt=125\r\na=rtpmap:108 H264/90000\r\na=rtcp-fb:108 goog-remb\│·····
r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;pro│·····
file-level-id=42e01f\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:124 red/90000\r\na=rtpmap:120 rtx/90000\r\na=fmtp:120 apt=124\r\na=rtpmap:123 ulpfec/9│·····
0000\r\nm=application 45176 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 62.44.138.138\r\na=candidate:328666875 1 udp 2113937151 172.20.10.2 60072 typ host generation │·····
0 network-cost 999\r\na=candidate:842163049 1 udp 1677729535 62.44.138.138 45176 typ srflx raddr 172.20.10.2 rport 60072 generation 0 network-cost 999\r\na=ice-ufrag:R│·····
mlv\r\na=ice-pwd:zvddVZUvnIYTF6Vpc02i78Yb\r\na=ice-options:trickle\r\na=fingerprint:sha-256 03:7D:3D:06:8C:7C:FF:B4:FB:87:BF:F3:D0:94:F9:38:67:B9:35:F9:04:E4:A4:A4:B5:│·····
FE:D3:25:CF:23:D0:AF\r\na=setup:actpass\r\na=mid:1\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n'}                                                              │·····
robotResponse                                                                                                                                                          │·····
{'sdp': 'v=0\r\no=- 3775295247 3775295247 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic:WMS *\r\nm=video 51853 UDP/TLS/RTP/SAVPF 96 97 102 12│·····
2 125 107\r\nc=IN IP4 172.16.10.218\r\na=sendonly\r\na=extmap:13 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 urn:ietf:params:rtp-hdrext:sd│·····
es:mid\r\na=mid:0\r\na=msid:8bc755f0-db35-48ab-ae61-edbc973e829e bf484ea5-a21d-4a72-a9f5-ed80105c8465\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc-group:FID 3096│·····
093486 2210961827\r\na=ssrc:3096093486 cname:{ec602860-f741-491a-97af-6635119e3a74}\r\na=ssrc:2210961827 cname:{ec602860-f741-491a-97af-6635119e3a74}\r\na=rtpmap:96 VP│·····
8/90000\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:10│·····
2 nack\r\na=rtcp-fb:102 nack pli\r\na=rtcp-fb:102 goog-remb\r\na=fmtp:102 packetization-mode=1;level-asymmetry-allowed=1;profile-level-id=42001f\r\na=rtpmap:122 rtx/90│·····
000\r\na=fmtp:122 apt=102\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=rtcp-fb:125 goog-remb\r\na=fmtp:125 packetization-mode=1;leve│·····
l-asymmetry-allowed=1;profile-level-id=42e01f\r\na=rtpmap:107 rtx/90000\r\na=fmtp:107 apt=125\r\na=candidate:f8d58ce5a70176a7ee2cc93f53c328a1 1 udp 2130706431 172.16.1│·····
0.218 51853 typ host\r\na=candidate:580b5f32035da7f14a30ea7a8d826c67 1 udp 2130706431 172.17.0.1 56363 typ host\r\na=candidate:48ecd84c84761deeb3419640f7577e2b 1 udp 1│·····
694498815 217.74.215.194 47421 typ srflx raddr 172.16.10.218 rport 51853\r\na=candidate:0ad8db753210ce9554cf251a9e51e792 1 udp 1694498815 217.74.215.194 47420 typ srfl│·····
x raddr 172.17.0.1 rport 56363\r\na=end-of-candidates\r\na=ice-ufrag:uXk2\r\na=ice-pwd:MrM2A3KnWPPYt4aLGjTo2m\r\na=fingerprint:sha-256 34:92:76:CB:CE:64:96:5D:C4:97:D9│·····
:E0:E7:C5:EE:4B:71:00:28:C7:0D:5F:33:9F:71:CD:0C:B6:5D:0D:DD:55\r\na=setup:active\r\nm=application 51853 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 172.16.10.218\r\n│·····
a=mid:1\r\na=sctp-port:5000\r\na=max-message-size:65536\r\na=candidate:f8d58ce5a70176a7ee2cc93f53c328a1 1 udp 2130706431 172.16.10.218 51853 typ host\r\na=candidate:58│·····
0b5f32035da7f14a30ea7a8d826c67 1 udp 2130706431 172.17.0.1 56363 typ host\r\na=candidate:48ecd84c84761deeb3419640f7577e2b 1 udp 1694498815 217.74.215.194 47421 typ srf│·····
lx raddr 172.16.10.218 rport 51853\r\na=candidate:0ad8db753210ce9554cf251a9e51e792 1 udp 1694498815 217.74.215.194 47420 typ srflx raddr 172.17.0.1 rport 56363\r\na=en│·····
d-of-candidates\r\na=ice-ufrag:uXk2\r\na=ice-pwd:MrM2A3KnWPPYt4aLGjTo2m\r\na=fingerprint:sha-256 34:92:76:CB:CE:64:96:5D:C4:97:D9:E0:E7:C5:EE:4B:71:00:28:C7:0D:5F:33:9│·····
F:71:CD:0C:B6:5D:0D:DD:55\r\na=setup:active\r\n', 'type': 'answer'}

robot happily prints out "Started WebRTC  "

dont know how to debug this. a pointer to how to get the status of the webrtcconection would be helpfull.

**Comment by dkumor** [comment]
I will take a closer look at this when I get back from the office later today. 

However, I would suggest trying to see if webrtc in general even works over your mobile connection - this can be checked by looking at raw webrtc javascript code (ie: not rtcbot at all), and trying to establish a connection between office and hotspot. That way, the problem can be isolated to either an issue with rtcbot, or an issue with webrtc. 

It might be the case that your mobile network's NAT simply does not permit establishing a direct connection, and therefore requires a TURN server.

**Comment by dkumor** [comment]
Based on the discussion in #5, this was fixed by adding the TURN server?

**Comment by dkumor** [comment]
I am going to assume that this issue was fixed. If you still have problems, please reopen it!

**Comment by rasmuspjohansson** [comment]
I’m still having problems but wanted to investigate it properly on my end
before asking for help.
I managed to get stuff to work but now getting unauthorized messages on the
turn server .

**Comment by dkumor** [comment]
OK, I'll reopen the issue - please let me know what you find out!

**Comment by rasmuspjohansson** [comment]
I still get some unauthorized meassages like this
16: session 001000000000000001: realm <104.248.247.99> user <>: incoming packet message processed, error 401: Unauthorized  
but it does not seem to be a problem becaus my conection works between two differetn wifi spots now.
problem I was having was caused by a mistake on my side aparantly.
