### ISSUE TITLE
Raspberry Pi OS: cryptography install fails, missing rustc compiler shenanigans

### ISSUE THREAD

**Issue by mbz4** [dkumor/rtcbot#46]
Hello and thank you for providing a sanity check in my trying times

I have been trying to install rtcbot on a **Pi 4B running Pi OS Lite**, latest.

When following instructions on either readme / docs, cryptography package, relying on the rust compiler (> v1.56.0) complains and haults installation.

Deep diving thru rust installation, pip upgrade, etc I wasn't able to resolve the issue nor have suggested solutions provided by rust folk on their discord or open/closed issues. 

description: **cryptography reports error during installation of rtcbot**
reason: **cryptography requires rust**
problem: **unable to install rust on Pi with rustup mis-identifying arm system as aarchm** 
meanwhile **apt install was successful but only up to rustc v1.48.0**

request: please help troubleshoot/resolve issue so I can get started w/ rtcbot on the Pi
happy to provide info to aid in this process and appreciate your time

Edit: would it be possible to use rustc v1.48.0 and downgrade cryptography to require that version of the compiler?

**Comment by mbz4** [comment]
` sudo pip3 install rtcbot
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting rtcbot
  Using cached https://www.piwheels.org/simple/rtcbot/rtcbot-0.2.4-py3-none-any.whl (42 kB)
Collecting aiortc (from rtcbot)
  Using cached https://www.piwheels.org/simple/aiortc/aiortc-1.5.0-cp39-cp39-linux_armv7l.whl (131 kB)
Collecting pyserial (from rtcbot)
  Using cached https://www.piwheels.org/simple/pyserial/pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting pyserial-asyncio (from rtcbot)
  Using cached https://www.piwheels.org/simple/pyserial-asyncio/pyserial_asyncio-0.6-py3-none-any.whl (7.5 kB)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from rtcbot) (1.19.5)
Requirement already satisfied: aiohttp in /usr/lib/python3/dist-packages (from rtcbot) (3.7.4)
Collecting SoundCard (from rtcbot)
  Using cached https://www.piwheels.org/simple/soundcard/SoundCard-0.4.2-py3-none-any.whl (40 kB)
Collecting inputs (from rtcbot)
  Using cached https://www.piwheels.org/simple/inputs/inputs-0.5-py2.py3-none-any.whl (33 kB)
Collecting pynmea2 (from rtcbot)
  Using cached https://www.piwheels.org/simple/pynmea2/pynmea2-1.19.0-py3-none-any.whl (30 kB)
Collecting aioice<1.0.0,>=0.9.0 (from aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/aioice/aioice-0.9.0-py3-none-any.whl (24 kB)
Collecting av<11.0.0,>=9.0.0 (from aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/av/av-10.0.0-cp39-cp39-linux_armv7l.whl (6.7 MB)
Requirement already satisfied: cffi>=1.0.0 in /usr/lib/python3/dist-packages (from aiortc->rtcbot) (1.14.5)
Collecting cryptography>=2.2 (from aiortc->rtcbot)
  Using cached cryptography-41.0.2.tar.gz (630 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting google-crc32c>=1.1 (from aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/google-crc32c/google_crc32c-1.5.0-py3-none-any.whl (13 kB)
Collecting pyee>=9.0.0 (from aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/pyee/pyee-11.0.0-py3-none-any.whl (15 kB)
Collecting pylibsrtp>=0.5.6 (from aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/pylibsrtp/pylibsrtp-0.8.0-cp39-cp39-linux_armv7l.whl (24 kB)
Collecting pyopenssl>=23.1.0 (from aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/pyopenssl/pyOpenSSL-23.2.0-py3-none-any.whl (59 kB)
Collecting dnspython>=2.0.0 (from aioice<1.0.0,>=0.9.0->aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/dnspython/dnspython-2.4.0-py3-none-any.whl (300 kB)
Collecting ifaddr>=0.2.0 (from aioice<1.0.0,>=0.9.0->aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/ifaddr/ifaddr-0.2.0-py3-none-any.whl (12 kB)
Requirement already satisfied: typing-extensions in /usr/lib/python3/dist-packages (from pyee>=9.0.0->aiortc->rtcbot) (3.7.4.3)
Collecting httpcore>=0.17.3 (from dnspython>=2.0.0->aioice<1.0.0,>=0.9.0->aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/httpcore/httpcore-0.17.3-py3-none-any.whl (74 kB)
Collecting sniffio<2.0,>=1.1 (from dnspython>=2.0.0->aioice<1.0.0,>=0.9.0->aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/sniffio/sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting h11<0.15,>=0.13 (from httpcore>=0.17.3->dnspython>=2.0.0->aioice<1.0.0,>=0.9.0->aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/h11/h11-0.14.0-py3-none-any.whl (58 kB)
Collecting anyio<5.0,>=3.0 (from httpcore>=0.17.3->dnspython>=2.0.0->aioice<1.0.0,>=0.9.0->aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/anyio/anyio-3.7.1-py3-none-any.whl (80 kB)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpcore>=0.17.3->dnspython>=2.0.0->aioice<1.0.0,>=0.9.0->aiortc->rtcbot) (2020.6.20)
Requirement already satisfied: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio<5.0,>=3.0->httpcore>=0.17.3->dnspython>=2.0.0->aioice<1.0.0,>=0.9.0->aiortc->rtcbot) (2.10)
Collecting exceptiongroup (from anyio<5.0,>=3.0->httpcore>=0.17.3->dnspython>=2.0.0->aioice<1.0.0,>=0.9.0->aiortc->rtcbot)
  Using cached https://www.piwheels.org/simple/exceptiongroup/exceptiongroup-1.1.2-py3-none-any.whl (14 kB)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cryptography (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [172 lines of output]
      /tmp/pip-build-env-gdslb41i/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        config = read_configuration(filepath, True, ignore_option_errors, dist)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-39
      creating build/lib.linux-aarch64-cpython-39/cryptography
      copying src/cryptography/__about__.py -> build/lib.linux-aarch64-cpython-39/cryptography
      copying src/cryptography/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography
      copying src/cryptography/exceptions.py -> build/lib.linux-aarch64-cpython-39/cryptography
      copying src/cryptography/utils.py -> build/lib.linux-aarch64-cpython-39/cryptography
      copying src/cryptography/fernet.py -> build/lib.linux-aarch64-cpython-39/cryptography
      creating build/lib.linux-aarch64-cpython-39/cryptography/x509
      copying src/cryptography/x509/base.py -> build/lib.linux-aarch64-cpython-39/cryptography/x509
      copying src/cryptography/x509/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/x509
      copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-aarch64-cpython-39/cryptography/x509
      copying src/cryptography/x509/name.py -> build/lib.linux-aarch64-cpython-39/cryptography/x509
      copying src/cryptography/x509/oid.py -> build/lib.linux-aarch64-cpython-39/cryptography/x509
      copying src/cryptography/x509/extensions.py -> build/lib.linux-aarch64-cpython-39/cryptography/x509
      copying src/cryptography/x509/general_name.py -> build/lib.linux-aarch64-cpython-39/cryptography/x509
      copying src/cryptography/x509/ocsp.py -> build/lib.linux-aarch64-cpython-39/cryptography/x509
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat
      copying src/cryptography/hazmat/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat
      copying src/cryptography/hazmat/_oid.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/_cipheralgorithm.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/_serialization.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/_asymmetric.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends
      copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings
      copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/pkcs7.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/serialization
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/kdf
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/ciphers
      copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/ciphers
      copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/ciphers
      copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/ciphers
      copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/ciphers
      copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/ciphers
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/types.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/asymmetric
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/twofactor
      copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/twofactor
      copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/twofactor
      copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/primitives/twofactor
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/backends/openssl
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/openssl
      copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/openssl
      copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/openssl
      copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/openssl
      running egg_info
      writing src/cryptography.egg-info/PKG-INFO
      writing dependency_links to src/cryptography.egg-info/dependency_links.txt
      writing requirements to src/cryptography.egg-info/requires.txt
      writing top-level names to src/cryptography.egg-info/top_level.txt
      reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c' under directory 'src/_cffi_src'
      warning: no files found matching '*.h' under directory 'src/_cffi_src'
      no previously-included directories found matching 'docs/_build'
      warning: no previously-included files found matching 'vectors'
      warning: no previously-included files matching '*' found under directory 'vectors'
      warning: no previously-included files found matching 'src/rust/target'
      warning: no previously-included files matching '*' found under directory 'src/rust/target'
      warning: no previously-included files matching '*' found under directory '.github'
      warning: no previously-included files found matching 'release.py'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'ci-constraints-requirements.txt'
      warning: no previously-included files found matching 'mypy.ini'
      adding license file 'LICENSE'
      adding license file 'LICENSE.APACHE'
      adding license file 'LICENSE.BSD'
      writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
      copying src/cryptography/py.typed -> build/lib.linux-aarch64-cpython-39/cryptography
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/_openssl.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/exceptions.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/pkcs7.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust
      copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust
      creating build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/__init__.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/dh.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/dsa.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/ed25519.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/ed448.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/hashes.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/hmac.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/kdf.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/poly1305.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/x25519.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      copying src/cryptography/hazmat/bindings/_rust/openssl/x448.pyi -> build/lib.linux-aarch64-cpython-39/cryptography/hazmat/bindings/_rust/openssl
      running build_ext
      running build_rust
      
          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation/ for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq/
          4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation/#rust
      
          Python: 3.9.2
          platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
          pip: n/a
          setuptools: 68.0.0
          setuptools_rust: 1.6.0
          rustc: n/a
          =============================DEBUG ASSISTANCE=============================
      
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      
      This package requires Rust >=1.56.0.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects`

**Comment by phamthanhnam** [comment]
There are no cryptography*.whl files for armv7l on pypi (see https://pypi.org/project/cryptography/#files) and building wheel failed on piwheels for latest version (41.0.2) of cryptography (see https://www.piwheels.org/project/cryptography/). That's the cause of your problem.

You can install rtcbot by using an older version of cryptography:
sudo pip3 install rtcbot cryptography==40.0.1

**Comment by mbz4** [comment]
Thank you very much @phamthanhnam for your reply, the suggested solution worked with the cryptography package downgrade.

However, two new issues emerged:


($...) ...rtcbot/examples/streaming $ python3 skeleton.py 
#### `1st: a warning message on rtcbot import, seemingly optional to address`
/usr/local/lib/python3.9/dist-packages/google_crc32c/__init__.py:29: RuntimeWarning: As the c extension couldn't be imported, `google-crc32c` is using a pure python implementation that is significantly slower. If possible, please configure a c build environment and compile the extension
  warnings.warn(_SLOW_CRC32C_WARNING, RuntimeWarning)

#### `2nd: traceback stating unsupported key type from openssl when trying to run examples/streaming/skeleton.py`
Traceback (most recent call last):
  File "/home/mbz/rtcbot/examples/streaming/skeleton.py", line 9, in <module>
    conn = RTCConnection()
  File "/usr/local/lib/python3.9/dist-packages/rtcbot/connection.py", line 381, in __init__
    self._rtc = RTCPeerConnection(configuration=rtcConfiguration)
  File "/usr/local/lib/python3.9/dist-packages/aiortc/rtcpeerconnection.py", line 294, in __init__
    self.__certificates = [RTCCertificate.generateCertificate()]
  File "/usr/local/lib/python3.9/dist-packages/aiortc/rtcdtlstransport.py", line 143, in generateCertificate
    key=crypto.PKey.from_cryptography_key(key),
  File "/home/mbz/.local/lib/python3.9/site-packages/OpenSSL/crypto.py", line 281, in from_cryptography_key
    raise TypeError("Unsupported key type")
TypeError: Unsupported key type

I'll look back thru the docs to see if there's any mention of this problem, it seems to be openssl & cryptography related, where a key is of a wrong type and/or outright absent - not generating?

Would appreciate further support and I understand this may be unrelated to the previous installation issue.

**Comment by mbz4** [comment]
I think all rtcbot examples are meant to be run with sudo and it solved the skeleton.py crypto key unsupported type problem.

**Comment by mbz4** [comment]
This library is full of suprises.

Got unknown error. Crashing video stream
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/rtcbot/tracks.py", line 173, in recv
    img = await self._frameSubscription.get()
  File "/usr/local/lib/python3.9/dist-packages/rtcbot/subscriptions.py", line 81, in get
    return await self._callback()
  File "/usr/local/lib/python3.9/dist-packages/rtcbot/base/base.py", line 365, in _get
    await self._getTask
  File "/usr/local/lib/python3.9/dist-packages/rtcbot/base/base.py", line 28, in get
    return await self._callback()
  File "/usr/local/lib/python3.9/dist-packages/rtcbot/base/base.py", line 361, in _get
    self._getTask = asyncio.ensure_future(self._subscription.get())
AttributeError: 'PiCamera' object has no attribute 'get'

Docs claim its supposed to work as a swap in replacement. I'm not sure about that ^^'
Appreciate thoughts on this head scratcher.

**Comment by mbz4** [comment]
Saw API docs outright omit image quality controls apart from CVCamera.
Is there a Discord for rtcbot to communicate more effectively?
