### ISSUE TITLE
Add TURN server tutorial

### ISSUE THREAD

**Issue by dkumor** [dkumor/rtcbot#5]
When going through a NAT, sometimes a TURN server is needed to complete a connection through restricted firewalls. This might be the case with #4 .

Since it is bound to be a fairly common situation, the tutorials should explicitly handle it, including a section on how to set up a TURN server, perhaps one of:
https://github.com/coturn/coturn
https://github.com/pion/turn

Or maybe even including a TURN server with rtcbot?

**Comment by rasmuspjohansson** [comment]
I can confirm that this seem to be the problem in #4  
made the robot script run on teh same digital ocean server and then the comunication works fine even though mylaptop and the robot runs on different networks.

I have installed coturn on the same digitalocean server as the server code is running on but dont know how to ad it to the rtcbot.RTCConnection . aiortc is not very clear on this either.
A function to call to add TURN server and  instructions on how to set up a turn server(not sure if I have configured my correctly)  would great

**Comment by dkumor** [comment]
I uploaded a new version that allows configuring ICE servers. The relevant python and javascript code is:

```python
from rtcbot import RTCConnection
from aiortc import RTCConfiguration, RTCIceServer

myConnection = RTCConnection(rtcConfiguration=RTCConfiguration([
                    RTCIceServer(urls="stun:stun.l.google.com:19302"),
                    RTCIceServer(urls="turn:myturnserver",
                        username="myusername",credential="mypassword")
                ]))
```

```javascript
var conn = new rtcbot.RTCConnection(rtcConfiguration=[
                    { urls: ["stun:stun.l.google.com:19302"] },
                    { urls: ["turn:myturnserver", 
                        username: "myusername", credential: "mypassword"], },
                ])
```

The detailed tutorial will have to wait a bit, since don't currently have time to write it.

**Comment by rasmuspjohansson** [comment]
great!
I had to modify your examples slightly in order to get it to work, here is what I used to set up the connection. 


javascript
var conn = new rtcbot.RTCConnection(rtcConfiguration=

 { iceServers: [{
                          urls: "turn:[mydigitaloceanservers.ip.ad.ress]:3478?transport=udp",
                          username: "myuserbame", 
                          credential: "mypassword"
                      }, {
                          urls: ["stun:stun.l.google.com:19302"]
                      }]
}

		);


python 

conn = RTCConnection(rtcConfiguration=RTCConfiguration([
                    RTCIceServer(urls="stun:stun.l.google.com:19302"),
                    RTCIceServer(urls="turn:mydigitaloceanservers.ip.ad.ress:3478",
                        username="myusername",credential="mypassword")
                ]))


i installed a turnserver on the same digitaloceanserver that was runnig the javascriptcode 
here is my turnserver.conf

 # you can listen ports 3478 and 5349 instead of 80/443
listening-port=3478
tls-listening-port=5349
user=myusername:mypassword

listening-ip=localhost



#no-stdout-log
verbose
fingerprint
lt-cred-mech
realm=testdrive.com
